### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by astronomersiva** [astronomersiva/www.sivasubramanyam.me#8]
- [x] Resize hero images for mobile.
- [x] Gradually remove Bootstrap.
- [x] Improve accessibility by continuing some work in done in 7d2be144e205bc80d883b29794d24696695c9223
- [x] Font size changes for posts
